In [1]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
import numpy as np 
arr = np.array(my_list) 
arr

array([1, 2, 3])

In [6]:
np.arange(0,11)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.rand(10)

array([0.64844489, 0.87269849, 0.77621529, 0.8359255 , 0.50721706,
       0.69472277, 0.41868558, 0.50698785, 0.91155339, 0.19274321])

In [9]:
np.random.rand(2,4)

array([[0.89195468, 0.43313415, 0.01506607, 0.14302776],
       [0.04714811, 0.29282956, 0.27963479, 0.54781463]])

In [11]:
np.random.randn(5)

array([ 0.40566772,  1.12562655, -1.0642771 , -0.67890294,  1.87446735])

In [12]:
np.random.randn(4,3)

array([[ 0.8218464 , -0.8759583 ,  0.68064699],
       [-0.30839144,  0.46454647,  0.02904163],
       [ 1.08498556,  1.18448888,  1.82112913],
       [-2.47596   ,  0.39581896,  0.58882956]])

In [13]:
np.random.randint(20,100, 10)

array([62, 25, 61, 49, 87, 53, 65, 42, 74, 52])