In [2]:
import numpy as np 

postive_numbers = np.arange(1, 1000, 4)
postive_numbers

array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
        53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
       105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
       157, 161, 165, 169, 173, 177, 181, 185, 189, 193, 197, 201, 205,
       209, 213, 217, 221, 225, 229, 233, 237, 241, 245, 249, 253, 257,
       261, 265, 269, 273, 277, 281, 285, 289, 293, 297, 301, 305, 309,
       313, 317, 321, 325, 329, 333, 337, 341, 345, 349, 353, 357, 361,
       365, 369, 373, 377, 381, 385, 389, 393, 397, 401, 405, 409, 413,
       417, 421, 425, 429, 433, 437, 441, 445, 449, 453, 457, 461, 465,
       469, 473, 477, 481, 485, 489, 493, 497, 501, 505, 509, 513, 517,
       521, 525, 529, 533, 537, 541, 545, 549, 553, 557, 561, 565, 569,
       573, 577, 581, 585, 589, 593, 597, 601, 605, 609, 613, 617, 621,
       625, 629, 633, 637, 641, 645, 649, 653, 657, 661, 665, 669, 673,
       677, 681, 685, 689, 693, 697, 701, 705, 709, 713, 717, 72

In [3]:
positive_numbers_as_fraction = 1 / (postive_numbers)
positive_numbers_as_fraction

array([1.        , 0.2       , 0.11111111, 0.07692308, 0.05882353,
       0.04761905, 0.04      , 0.03448276, 0.03030303, 0.02702703,
       0.02439024, 0.02222222, 0.02040816, 0.01886792, 0.01754386,
       0.01639344, 0.01538462, 0.01449275, 0.01369863, 0.01298701,
       0.01234568, 0.01176471, 0.01123596, 0.01075269, 0.01030928,
       0.00990099, 0.00952381, 0.00917431, 0.00884956, 0.00854701,
       0.00826446, 0.008     , 0.00775194, 0.0075188 , 0.00729927,
       0.0070922 , 0.00689655, 0.00671141, 0.00653595, 0.00636943,
       0.00621118, 0.00606061, 0.00591716, 0.00578035, 0.00564972,
       0.00552486, 0.00540541, 0.00529101, 0.00518135, 0.00507614,
       0.00497512, 0.00487805, 0.00478469, 0.00469484, 0.00460829,
       0.00452489, 0.00444444, 0.00436681, 0.00429185, 0.00421941,
       0.00414938, 0.00408163, 0.00401606, 0.00395257, 0.00389105,
       0.00383142, 0.00377358, 0.00371747, 0.003663  , 0.00361011,
       0.00355872, 0.00350877, 0.00346021, 0.00341297, 0.00336

In [4]:
negative_numbers_as_fraction = 1 / (postive_numbers + 2)
negative_numbers_as_fraction

array([0.33333333, 0.14285714, 0.09090909, 0.06666667, 0.05263158,
       0.04347826, 0.03703704, 0.03225806, 0.02857143, 0.02564103,
       0.02325581, 0.0212766 , 0.01960784, 0.01818182, 0.01694915,
       0.01587302, 0.01492537, 0.01408451, 0.01333333, 0.01265823,
       0.01204819, 0.01149425, 0.01098901, 0.01052632, 0.01010101,
       0.00970874, 0.00934579, 0.00900901, 0.00869565, 0.00840336,
       0.00813008, 0.00787402, 0.00763359, 0.00740741, 0.00719424,
       0.00699301, 0.00680272, 0.00662252, 0.00645161, 0.00628931,
       0.00613497, 0.00598802, 0.00584795, 0.00571429, 0.00558659,
       0.00546448, 0.00534759, 0.0052356 , 0.00512821, 0.00502513,
       0.00492611, 0.00483092, 0.00473934, 0.00465116, 0.00456621,
       0.0044843 , 0.00440529, 0.004329  , 0.00425532, 0.0041841 ,
       0.00411523, 0.00404858, 0.00398406, 0.00392157, 0.003861  ,
       0.00380228, 0.00374532, 0.00369004, 0.00363636, 0.00358423,
       0.00353357, 0.00348432, 0.00343643, 0.00338983, 0.00334

In [5]:
pie_number = 4 * (sum(positive_numbers_as_fraction) - sum(negative_numbers_as_fraction))
pie_number

3.139592655589775